### ISSUE TITLE
scapegoat broken

### ISSUE THREAD

**Issue by JohnReedLOL** [scapegoat-scala/sbt-scapegoat#82] opened 2018-10-07 03:24 UTC
See: https://imgur.com/a/CHDp1q7

**Comment by BalmungSan** [comment] 2018-10-07 23:59
Maybe this is a duplicate of #77 ?

**Comment by Johnnei** [comment] 2024-11-24 10:16
Very likely yes. https://github.com/scapegoat-scala/sbt-scapegoat/pull/157 made the out of the box experience a lot nicer with regard to compatible version selection.

**Closed by Johnnei** 2024-11-24 10:16 UTC
